// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeMessage struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeMessage) Reset()         { *m = TimeMessage{} }
func (m *TimeMessage) String() string { return proto.CompactTextString(m) }
func (*TimeMessage) ProtoMessage()    {}
func (*TimeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *TimeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeMessage.Unmarshal(m, b)
}
func (m *TimeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeMessage.Marshal(b, m, deterministic)
}
func (m *TimeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeMessage.Merge(m, src)
}
func (m *TimeMessage) XXX_Size() int {
	return xxx_messageInfo_TimeMessage.Size(m)
}
func (m *TimeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TimeMessage proto.InternalMessageInfo

func (m *TimeMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type EchoRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{1}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type EchoReply struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EchoReply) Reset()         { *m = EchoReply{} }
func (m *EchoReply) String() string { return proto.CompactTextString(m) }
func (*EchoReply) ProtoMessage()    {}
func (*EchoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{2}
}

func (m *EchoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoReply.Unmarshal(m, b)
}
func (m *EchoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoReply.Marshal(b, m, deterministic)
}
func (m *EchoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoReply.Merge(m, src)
}
func (m *EchoReply) XXX_Size() int {
	return xxx_messageInfo_EchoReply.Size(m)
}
func (m *EchoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoReply.DiscardUnknown(m)
}

var xxx_messageInfo_EchoReply proto.InternalMessageInfo

func (m *EchoReply) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *EchoReply) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*TimeMessage)(nil), "TimeMessage")
	proto.RegisterType((*EchoRequest)(nil), "EchoRequest")
	proto.RegisterType((*EchoReply)(nil), "EchoReply")
}

func init() {
	proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0)
}

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b,
	0xa0, 0x0a, 0xa4, 0xd1, 0x15, 0xa4, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x24, 0x95, 0xdc, 0xb9, 0xb8,
	0x43, 0x32, 0x73, 0x53, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x2c, 0xb8, 0x38, 0xe1,
	0xda, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0xfa, 0xf5, 0x60, 0xfa, 0xf5,
	0x42, 0x60, 0x2a, 0x82, 0x10, 0x8a, 0x95, 0x14, 0xb9, 0xb8, 0x5d, 0x93, 0x33, 0xf2, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0xc0, 0x66, 0x70,
	0x06, 0x81, 0xd9, 0x4a, 0x91, 0x5c, 0x9c, 0x10, 0x25, 0x05, 0x39, 0x95, 0xe4, 0xdb, 0x04, 0x37,
	0x9a, 0x09, 0x61, 0xb4, 0x51, 0x1c, 0x17, 0x5b, 0x30, 0x38, 0x50, 0x84, 0x94, 0xb8, 0x58, 0x40,
	0x96, 0x08, 0xf1, 0xe8, 0x21, 0x39, 0x47, 0x8a, 0x4b, 0x0f, 0x6e, 0xb3, 0x12, 0x83, 0x90, 0x01,
	0x17, 0x0b, 0xc8, 0x64, 0x21, 0x31, 0x0c, 0x0b, 0x5d, 0x41, 0x41, 0x23, 0xc5, 0xa3, 0x87, 0x14,
	0x26, 0x4a, 0x0c, 0x06, 0x8c, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xd6, 0x05, 0x49, 0x49, 0x6c, 0x60,
	0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x99, 0xd3, 0x3e, 0x83, 0x01, 0x00, 0x00,
}
